# Form implementation generated from reading ui file 'plius_minus.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(431, 340)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plius = QtWidgets.QPushButton(parent=self.centralwidget)
        self.plius.setGeometry(QtCore.QRect(40, 80, 75, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 207, 123))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 207, 123))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 207, 123))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        self.plius.setPalette(palette)
        self.plius.setObjectName("plius")
        self.minus = QtWidgets.QPushButton(parent=self.centralwidget)
        self.minus.setGeometry(QtCore.QRect(270, 80, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minus.setFont(font)
        self.minus.setObjectName("minus")
        self.ivedimas = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.ivedimas.setGeometry(QtCore.QRect(130, 110, 111, 21))
        self.ivedimas.setObjectName("ivedimas")
        self.line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(130, 150, 113, 21))
        self.line.setObjectName("line")
        self.txtlabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.txtlabel.setGeometry(QtCore.QRect(160, 80, 49, 16))
        self.txtlabel.setObjectName("txtlabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 431, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.plius.setText(_translate("MainWindow", "Pliusas"))
        self.minus.setText(_translate("MainWindow", "Minusas"))
        self.ivedimas.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2</p></body></html>"))
        self.line.setText(_translate("MainWindow", "3"))
        self.txtlabel.setText(_translate("MainWindow", "1"))
