# Form implementation generated from reading ui file 'dizainas.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(565, 292)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.veiksmas = QtWidgets.QLabel(parent=self.centralwidget)
        self.veiksmas.setGeometry(QtCore.QRect(20, 30, 131, 16))
        self.veiksmas.setObjectName("veiksmas")
        self.url = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.url.setGeometry(QtCore.QRect(20, 60, 471, 21))
        self.url.setObjectName("url")
        self.button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button.setGeometry(QtCore.QRect(20, 90, 75, 41))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(10)
        font.setBold(True)
        self.button.setFont(font)
        self.button.setObjectName("button")
        self.atsakymas = QtWidgets.QLabel(parent=self.centralwidget)
        self.atsakymas.setGeometry(QtCore.QRect(20, 150, 301, 21))
        self.atsakymas.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.atsakymas.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.atsakymas.setObjectName("atsakymas")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 565, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.veiksmas.setText(_translate("MainWindow", "Įveskite puslapio linką:"))
        self.button.setText(_translate("MainWindow", "OK"))
        self.atsakymas.setText(_translate("MainWindow", "TextLabel"))
