# Form implementation generated from reading ui file 'dizainas.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(541, 426)
        self.centralwidget = QtWidgets.QWidget(parent=mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.vardas = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.vardas.setGeometry(QtCore.QRect(30, 60, 361, 51))
        self.vardas.setObjectName("vardas")
        self.vardui = QtWidgets.QLabel(parent=self.centralwidget)
        self.vardui.setGeometry(QtCore.QRect(40, 20, 171, 31))
        self.vardui.setObjectName("vardui")
        self.pavardei = QtWidgets.QLabel(parent=self.centralwidget)
        self.pavardei.setGeometry(QtCore.QRect(30, 110, 171, 31))
        self.pavardei.setObjectName("pavardei")
        self.pavarde = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.pavarde.setGeometry(QtCore.QRect(30, 140, 361, 51))
        self.pavarde.setObjectName("pavarde")
        self.metai = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.metai.setGeometry(QtCore.QRect(30, 220, 111, 51))
        self.metai.setObjectName("metai")
        self.metams = QtWidgets.QLabel(parent=self.centralwidget)
        self.metams.setGeometry(QtCore.QRect(30, 200, 171, 31))
        self.metams.setObjectName("metams")
        self.mygtukas = QtWidgets.QPushButton(parent=self.centralwidget)
        self.mygtukas.setGeometry(QtCore.QRect(210, 230, 211, 41))
        self.mygtukas.setObjectName("mygtukas")
        self.atsakymas = QtWidgets.QLabel(parent=self.centralwidget)
        self.atsakymas.setGeometry(QtCore.QRect(40, 310, 351, 31))
        self.atsakymas.setObjectName("atsakymas")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 541, 22))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.vardui.setText(_translate("mainWindow", "Įveskite vardą:"))
        self.pavardei.setText(_translate("mainWindow", "Įveskite pavardę:"))
        self.metams.setText(_translate("mainWindow", "Įveskite gimimo metus:"))
        self.mygtukas.setText(_translate("mainWindow", "Įvesti"))
        self.atsakymas.setText(_translate("mainWindow", "TextLabel"))
